parameters:
    github.username: '%env(GITHUB_USERNAME)%'
    github.personal_access_token: '%env(GITHUB_PERSONAL_ACCESS_TOKEN)%'
    github.api.url: 'https://api.github.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $githubUsername: '%github.username%'
            string $githubPersonalAccessToken: '%github.personal_access_token%'
            string $githubApiUrl: '%github.api.url%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/**/Dto'
            - '../src/Entity/'
            - '../src/**/Exception'
            - '../src/Kernel.php'
